import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import sassPlugin from "esbuild-plugin-sass";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === "production";

// JavaScript bundle configuration
const jsContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["./src/script/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	loader: {
		".css": "text"
	},
	plugins: [
		sassPlugin({
			filter: /\.(sass|scss)$/,
			type: "css-text",
		})
	],
});

// CSS bundle configuration
const cssContext = await esbuild.context({
	entryPoints: ["./src/style/styles.sass"],
	bundle: true,
	outfile: "styles.css",
	minify: prod,
	loader: {
		".sass": "css",
		".scss": "css",
	},
	plugins: [
		sassPlugin({
			filter: /\.(sass|scss)$/,
		})
	],
});

if (prod) {
	await jsContext.rebuild();
	await cssContext.rebuild();
	process.exit(0);
} else {
	await jsContext.watch();
	await cssContext.watch();
}
